wandb_version: 1

J:
  value: 4
Q:
  value: 48
channel_1:
  value: 4
channel_2:
  value: 32
channel_3:
  value: 128
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 2
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0009490518087481864
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
