wandb_version: 1

J:
  value: 3
Q:
  value: 20
channel_1:
  value: 2
channel_2:
  value: 16
channel_3:
  value: 32
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 5
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0009739388031873316
optimizer:
  value: nadam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
