wandb_version: 1

J:
  value: 4
Q:
  value: 48
channel_1:
  value: 4
channel_2:
  value: 16
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 3
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0005318672543148906
optimizer:
  value: sgd
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
