wandb_version: 1

J:
  value: 2
Q:
  value: 12
channel_1:
  value: 2
channel_2:
  value: 16
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 4
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 0.0008384819746621176
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
