wandb_version: 1

J:
  value: 4
Q:
  value: 24
channel_1:
  value: 2
channel_2:
  value: 8
channel_3:
  value: 32
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 5
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0009633037382464056
optimizer:
  value: nadam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
