wandb_version: 1

J:
  value: 2
Q:
  value: 48
channel_1:
  value: 2
channel_2:
  value: 32
channel_3:
  value: 96
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 2
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0001357635409755054
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
