wandb_version: 1

J:
  value: 3
Q:
  value: 64
channel_1:
  value: 8
channel_2:
  value: 32
channel_3:
  value: 32
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 3
kernel_width:
  value: 2
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.00011584207549460454
optimizer:
  value: nadam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
