wandb_version: 1

J:
  value: 3
Q:
  value: 20
channel_1:
  value: 8
channel_2:
  value: 8
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 5
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0006624761223048218
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
