wandb_version: 1

J:
  value: 3
Q:
  value: 48
channel_1:
  value: 4
channel_2:
  value: 32
channel_3:
  value: 32
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 4
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0006322860699986905
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
