wandb_version: 1

J:
  value: 4
Q:
  value: 52
channel_1:
  value: 2
channel_2:
  value: 32
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 4
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 1.187945909214489e-05
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
