wandb_version: 1

J:
  value: 2
Q:
  value: 64
channel_1:
  value: 8
channel_2:
  value: 8
channel_3:
  value: 32
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 3
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0005685116625624582
optimizer:
  value: sgd
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
