wandb_version: 1

J:
  value: 2
Q:
  value: 16
channel_1:
  value: 8
channel_2:
  value: 32
channel_3:
  value: 96
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 2
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.00032877807548057866
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
