wandb_version: 1

J:
  value: 2
Q:
  value: 64
channel_1:
  value: 8
channel_2:
  value: 16
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 3
kernel_width:
  value: 2
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0004525467181531518
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
