wandb_version: 1

J:
  value: 4
Q:
  value: 20
channel_1:
  value: 8
channel_2:
  value: 16
channel_3:
  value: 96
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 3
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.00024537589192546273
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
