wandb_version: 1

J:
  value: 2
Q:
  value: 64
channel_1:
  value: 2
channel_2:
  value: 32
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 2
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 9.759854965930464e-05
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
