wandb_version: 1

J:
  value: 3
Q:
  value: 12
channel_1:
  value: 8
channel_2:
  value: 32
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 5
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 0.0004305047061634067
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
