wandb_version: 1

J:
  value: 2
Q:
  value: 36
channel_1:
  value: 4
channel_2:
  value: 16
channel_3:
  value: 128
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 3
kernel_width:
  value: 4
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 0.00032458001375542956
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
