wandb_version: 1

J:
  value: 4
Q:
  value: 12
channel_1:
  value: 8
channel_2:
  value: 8
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 2
kernel_width:
  value: 2
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 3.931606523892662e-05
optimizer:
  value: sgd
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
