wandb_version: 1

J:
  value: 4
Q:
  value: 16
channel_1:
  value: 8
channel_2:
  value: 16
channel_3:
  value: 64
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 5
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0009869402389055342
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
