wandb_version: 1

J:
  value: 4
Q:
  value: 20
channel_1:
  value: 4
channel_2:
  value: 8
channel_3:
  value: 128
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 3
kernel_width:
  value: 2
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0004374613694571749
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
