wandb_version: 1

J:
  value: 3
Q:
  value: 52
channel_1:
  value: 4
channel_2:
  value: 32
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 3
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.00017608522568140998
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
