wandb_version: 1

J:
  desc: null
  value: 3
Q:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1678740417.296747
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 3
      - 23
      - 37
      4: 3.10.4
      5: 0.13.4
      8:
      - 5
channel_1:
  desc: null
  value: 2
channel_2:
  desc: null
  value: 32
channel_3:
  desc: null
  value: 128
dense:
  desc: null
  value: 1
epochs:
  desc: null
  value: 200
kernel_length:
  desc: null
  value: 4
kernel_width:
  desc: null
  value: 3
layer:
  desc: null
  value: 2
loss_function:
  desc: null
  value: mine_cross
lr:
  desc: null
  value: 0.000902625184884403
optimizer:
  desc: null
  value: sgd
project_name:
  desc: null
  value: scattering_2.5k_100
wrong_key:
  desc: null
  value: 0
