wandb_version: 1

J:
  value: 4
Q:
  value: 8
channel_1:
  value: 2
channel_2:
  value: 32
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 5
kernel_width:
  value: 3
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0005499931581031336
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
