wandb_version: 1

J:
  value: 4
Q:
  value: 24
channel_1:
  value: 4
channel_2:
  value: 8
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 4
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0005847
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 224
