wandb_version: 1

J:
  value: 4
Q:
  value: 8
channel_1:
  value: 2
channel_2:
  value: 16
channel_3:
  value: 64
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 5
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.000733950165470385
optimizer:
  value: adam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
