wandb_version: 1

J:
  value: 2
Q:
  value: 52
channel_1:
  value: 2
channel_2:
  value: 8
channel_3:
  value: 32
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 3
kernel_width:
  value: 3
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.0006087644557185197
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
