wandb_version: 1

J:
  value: 3
Q:
  value: 24
channel_1:
  value: 8
channel_2:
  value: 8
channel_3:
  value: 96
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 2
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 1.9445507754455927e-05
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
