wandb_version: 1

J:
  value: 2
Q:
  value: 24
epochs:
  value: 50
kernel:
  value: 2
kernel_width:
  value: 16
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.00010258692690294446
optimizer:
  value: nadam
wrong_key:
  value: 0
