wandb_version: 1

J:
  value: 4
Q:
  value: 36
channel_1:
  value: 8
channel_2:
  value: 32
channel_3:
  value: 128
dense:
  value: 1
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 4
layer:
  value: 3
loss_function:
  value: mine_cross
lr:
  value: 0.00027998464210531954
optimizer:
  value: nadam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
