wandb_version: 1

J:
  desc: null
  value: 5
Q:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1664984038.446642
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.5
      5: 0.13.3
      8:
      - 5
epochs:
  desc: null
  value: 1000
loss:
  desc: null
  value: mse
lr:
  desc: null
  value: 0.0005716090182918798
optimizer:
  desc: null
  value: adam
