wandb_version: 1

J:
  value: 1
Q:
  value: 20
epochs:
  value: 50
kernel:
  value: 3
kernel_width:
  value: 16
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 0.00016640545220599032
optimizer:
  value: rmsprop
wrong_key:
  value: 0
