wandb_version: 1

J:
  value: 1
Q:
  value: 16
epochs:
  value: 50
kernel:
  value: 4
kernel_width:
  value: 32
layer:
  value: 2
loss_function:
  value: mine_cross
lr:
  value: 0.0004313265631849196
optimizer:
  value: adam
wrong_key:
  value: 0
