wandb_version: 1

J:
  value: 3
Q:
  value: 64
channel_1:
  value: 2
channel_2:
  value: 16
channel_3:
  value: 96
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 4
layer:
  value: 4
loss_function:
  value: mine_cross
lr:
  value: 0.00027693584283679424
optimizer:
  value: nadam
project_name:
  value: scattering_2.5k_100
wrong_key:
  value: 0
