wandb_version: 1

J:
  desc: null
  value: 1
Q:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1665217192.780914
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.5
      5: 0.13.3
      8:
      - 5
epochs:
  desc: null
  value: 50
kernel:
  desc: null
  value: 4
kernel_width:
  desc: null
  value: 32
layer:
  desc: null
  value: 2
loss_function:
  desc: null
  value: mine_cross
lr:
  desc: null
  value: 0.0004313265631849196
optimizer:
  desc: null
  value: adam
wrong_key:
  desc: null
  value: 0
