wandb_version: 1

channel_1:
  value: 8
channel_2:
  value: 32
channel_3:
  value: 256
dense:
  value: 2
epochs:
  value: 200
kernel_length:
  value: 4
kernel_width:
  value: 3
layer:
  value: 7
loss_function:
  value: mine_cross
lr:
  value: 0.0007848
optimizer:
  value: rmsprop
project_name:
  value: scattering_2.5k_100
windows:
  value: 84
wrong_key:
  value: 0
