wandb_version: 1

J:
  desc: null
  value: 4
Q:
  desc: null
  value: 48
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1678553185.647372
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.4
      5: 0.13.4
      8:
      - 5
channel_1:
  desc: null
  value: 4
channel_2:
  desc: null
  value: 16
channel_3:
  desc: null
  value: 64
dense:
  desc: null
  value: 1
epochs:
  desc: null
  value: 200
kernel_length:
  desc: null
  value: 5
kernel_width:
  desc: null
  value: 3
layer:
  desc: null
  value: 2
loss_function:
  desc: null
  value: mine_cross
lr:
  desc: null
  value: 0.0005318672543148906
optimizer:
  desc: null
  value: sgd
project_name:
  desc: null
  value: scattering_2.5k_100
wrong_key:
  desc: null
  value: 0
